import { getDifficulty } from '../core/engine';
import { formatDuration, rankingKey, type HistoryData, type RoundRecord } from '../storage/history';

const dateFormat = new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false });
const results: Record<RoundRecord['result'], string> = { WON: '清盘', LOST: '触底', ABANDONED: '重开', TIMEOUT: '时间到', SETTLED: '主动结算' };
export function historyMarkup(data: HistoryData, top: boolean, board: string, page: number, mobile: boolean): string {
  const all = (top ? data.top : data.recent).filter(r => rankingKey(r) === board);
  const pageSize = top ? 10 : 20;
  const rows = all.slice(page * pageSize, (page + 1) * pageSize);
  const latest = data.recent.find(r => rankingKey(r) === board && r.result !== 'ABANDONED')?.id;
  const head = `<button class="history-close" data-close-modal aria-label="关闭记录">×</button><p class="eyebrow">PERSONAL / LOCAL</p><div class="history-title"><h2>${top ? '排行榜' : '历史记录'}</h2><button id="history-toggle" class="text-button">${top ? '查看历史' : '查看排行'}</button></div><div class="history-rules"><span>得分 = 基础分 × 难度系数</span><details><summary>排名规则</summary><p>简单 ×1 · 普通 ×1.5 · 困难 ×2。结算后入榜，重开不入榜；同分时用时较短者在前，每个榜单保留前十名。全部成绩均为你的本地记录。</p></details></div><div class="history-segments" role="group" aria-label="选择榜单">${[['endless','无尽'],['timed-300000','5 分钟'],['timed-600000','10 分钟']].map(([key,label]) => `<button data-board="${key}" aria-pressed="${key === board}">${label}</button>`).join('')}</div>`;
  const body = mobile ? `<ol class="ranking-list">${rows.map((r,i) => `<li class="ranking-row${r.id === latest ? ' recent-best' : ''}"><span class="rank-number">${String(page * pageSize + i + 1).padStart(2,'0')}</span><div class="rank-score"><strong>${r.score.toLocaleString('zh-CN')}</strong><small>${r.rawScore ?? r.score} × ${r.multiplier ?? 1}</small></div><div class="rank-status"><span>${getDifficulty(r.difficulty).label}</span><small>${results[r.result]}${r.id === latest ? ' · 最近' : ''}</small></div><div class="rank-meta"><time>${dateFormat.format(r.startedAt)}</time><span>${formatDuration(r.elapsedMs)} · ${r.shots} 球</span></div></li>`).join('') || '<li class="history-empty">暂无记录，完成一局后成绩会显示在这里。</li>'}</ol>` : `<div class="history-scroll"><table><thead><tr><th>#</th><th>开始时间</th><th>分数</th><th>难度 / 结果</th><th>用时 / 发射</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${page * pageSize + i + 1}</td><td>${dateFormat.format(r.startedAt)}</td><td><strong>${r.score.toLocaleString('zh-CN')}</strong><small class="score-formula">${r.rawScore ?? r.score} × ${r.multiplier ?? 1}</small></td><td>${getDifficulty(r.difficulty).label} / ${results[r.result]}</td><td>${formatDuration(r.elapsedMs)} / ${r.shots}</td></tr>`).join('') || '<tr><td colspan="5">暂无记录，完成一局后会自动保存在这里。</td></tr>'}</tbody></table></div>`;
  return head + body + (!top ? `<div class="history-pagination"><button id="history-prev" aria-label="上一页" ${page === 0 ? 'disabled' : ''}>‹</button><span>${page + 1} / ${Math.max(1,Math.ceil(all.length / pageSize))}</span><button id="history-next" aria-label="下一页" ${(page + 1) * pageSize >= all.length ? 'disabled' : ''}>›</button></div>` : '');
}
